### ISSUE TITLE
Unit test

### ISSUE THREAD

**Issue by IndianGhost** [kaoutharElbakouri/Implement_ArrayList_From_Scratch#1]
I think It was a great idea to think of creating an ArrayList, I know that's probably for pedagogic purposes. Anyways, I advice you to add a class of unit test. It would be the opportunity to learn to write a quality code. Good luck 💯

**Comment by kaoutharElbakouri** [comment]
Bonjour Mr. Achraf,
Je suis désolée je viens juste de vous répondre.
Merci beaucoup pour votre remarque, je vais essayer d'ajouter la classe que
vous m'avez indiquer pour le test.
Cordialement.

Le mer. 20 avr. 2022 à 16:40, Achraf BELLAALI ***@***.***> a
écrit :

**Comment by IndianGhost** [comment]
@kaoutharElbakouri Pas de soucim Si vous arriviez pas à en implémenter, vous pourriez me contacter pour vous proposer une solution

**Comment by IndianGhost** [comment]
I had added a pull request to resolve this problem, you can check it below:
https://github.com/kaoutharElbakouri/Implement_ArrayList_From_Scratch/pull/2
